services:
  postgres:
    image: postgres:16-alpine
    container_name: hobby-baseline-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hobby_user
      POSTGRES_PASSWORD: hobby_password
      POSTGRES_DB: hobby_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hobby_user -d hobby_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: